### ISSUE TITLE
Proposal to add CorrectSorted and DecodeSorted

### ISSUE THREAD

**Issue by cristaloleg** [vivint/infectious#3]
Firstly, thank you for creating Infectious!

In method `Decode` we're sorting `shares`, but `shares` are already sorted in `Correct` method.
So we're doing work twice and for not so big amount of pieces this will lower the performance(two times of O(N * LogN) work is done)

I'm proposing to create two methods, which expects `shares` that are already sorted and with a linear check ensure that they're sorted (two times O(N)).

I've it already done it on my branch, will push as far as you'll agree with my proposal.

Thanks.

**Comment by zeebo** [comment]
I think the cost of a sort on an already sorted list is much smaller than sorting the first time, so I erred on the side of safety.

Do you have any benchmarks showing that sorting is taking a significant runtime that justifies the more complex api?

**Comment by cristaloleg** [comment]
Sorry, no real examples, just thoughts. I get your point. You can close issue if you want to.

**Comment by zeebo** [comment]
I'll close this until we have some evidence that it causes a significant performance degradation.
