### ISSUE TITLE
"not enough shares" when using 1 parity share

### ISSUE THREAD

**Issue by marcboeker** [vivint/infectious#4]
Hi,

when using 1 parity share, I always get the error "not enough shares". That's because the following code uses int instead of float:

```
func (fc *FEC) berlekampWelch(shares []Share, index int) ([]byte, error) {
	k := fc.k        // required size
	r := len(shares) // required + redundancy size
	e := (r - k) / 2 // deg of E polynomial
	q := e + k       // def of Q polynomial

	fmt.Println(k, r, e, q, index)

	if e == 0 {
		return nil, Error.New("not enough shares")
	}
```

When using a configuration of e.g. 4 data and 1 parity share, we have a total of 5. In the equitation above, k = 4, r = 5, e = (5 - 4) / 2 = 0.5
But since you are using int, e = (5 - 4) / 2 = 0 which triggers "not enough shares".

Is it not intended to use only 1 parity share?

Thanks,
Marc

**Comment by cristaloleg** [comment]
Does it make sense to use only 1 share at all?
If this share will have corrupted data it will not be possible to restore the information, afaik.

**Comment by marcboeker** [comment]
I'm testing a storage system locally and didn't want to use the 7 data, 3 parity configuration which is being used in prod. So I'm using a 1 data, 1 parity configuration to speed up the testing process.

But even using 1 data and 1 parity setup should at least give me redundancy?

**Comment by zeebo** [comment]
You cannot do error correction with only one parity share, just detection: with 1 data share and 1 parity share, you can tell that they don't match each other, but you can't tell which one is correct. Since it was hitting that code path, it detected errors and told you that there were not enough shares to do correction.

**Comment by marcboeker** [comment]
Thanks for the explanation.
